.gitmodules, build/devops_gated.yml
Add C build tools repo as dependency & enable requirements traceability leg
=> Add C build tools repo as dependency

inc/azure_c_util/etwlogger_driver.h, src/etwlogger_driver.c, src/etwxlogging.c
=> Add missing etw files

CMakeLists.txt
Add traceability project in the .sln
=> Add traceability project in the .sln

CMakeLists.txt, build/devops_gated.yml
Add traceability option in CMakeLists.Txt
=> Add traceability option in CMakeLists.Txt

devdoc/constbuffer_array_batcher_nv_requirements.md, src/constbuffer_array_batcher_nv.c, tests/constbuffer_array_batcher_nv_ut/constbuffer_array_batcher_nv_ut.c
Rename of constbuffer_array_batcher => constbuffer_array_batcher_nv part 2
=> Rename of constbuffer_array_batcher => constbuffer_array_batcher_nv part 2

tests/azure_base64_ut/azure_base64_ut.c, tests/buffer_ut/buffer_ut.c, tests/constbuffer_array_batcher_nv_ut/constbuffer_array_batcher_nv_ut.c, tests/constbuffer_array_ut/constbuffer_array_ut.c, tests/constbuffer_ut/constbuffer_ut.c, tests/gballoc_ut/gballoc_ut.c, tests/interlocked_hl_win32_ut/interlocked_hl_win32_ut.c, tests/lock_ut/lock_ut.c, tests/map_ut/map_ut.c, tests/platform_win32_ut/platform_win32_ut.c, tests/refcount_ut/refcount_ut.c, tests/singlylinkedlist_ut/singlylinkedlist_ut.c, tests/srw_lock_ut/srw_lock_ut.c, tests/strings_ut/strings_ut.c, tests/thandle_ut/thandle_ut.c, tests/tickcounter_ut/tickcounter_ut.c, tests/timer_win32_ut/timer_ut.c, tests/uniqueid_ut/uniqueid_ut_win32.c
Combine IGNORED_NUM_ARG and IGNORED_PTR_ARG
=> Combine IGNORED_NUM_ARG and IGNORED_PTR_ARG

inc/azure_c_util/thandle.h, tests/thandle_ut/thandle_ut.c
Adds a new _INSPECT function used only for debugging.
=> enhance THANDLE

adapters/timer.c, inc/azure_c_util/timer.h, tests/reals/real_timer.h, tests/reals/real_timer_renames.h
When writes take 1-2 ms, the ms resolution is misleading.
=> add timer_us

src/constbuffer.c, src/constbuffer_array.c, tests/refcount_ut/some_refcount_impl.c, tests/thandle_ut/thandle_flex_user.c, tests/thandle_ut/thandle_ut.c
Disable compiler warning 4200 for MSC
=> Disable w4200 globally

tests/strings_ut/strings_ut.c, tests/thandle_ut/thandle_ut.c
Fix warnings and have warnings as errors for C util
=> Fix warnings and have warnings as errors for C util

src/sm.c
=> Remove one leftover pragma

inc/azure_c_util/thandle.h, src/azure_base64.c, src/buffer.c, src/constbuffer.c, src/constbuffer_array.c, src/constbuffer_array_batcher_nv.c, src/crt_abstractions.c, src/map.c, src/rc_string.c, src/singlylinkedlist.c, src/sm.c, src/strings.c, src/uuid.c, tests/azure_base64_ut/azure_base64_ut.c, tests/buffer_ut/buffer_ut.c, tests/constbuffer_array_batcher_nv_ut/constbuffer_array_batcher_nv_ut.c, tests/constbuffer_array_ut/constbuffer_array_ut.c, tests/constbuffer_ut/constbuffer_ut.c, tests/crtabstractions_ut/crtabstractions_ut.c, tests/map_ut/map_ut.c, tests/singlylinkedlist_ut/singlylinkedlist_ut.c, tests/sm_int/sm_int.c, tests/sm_ut/sm_ut.c, tests/strings_ut/strings_ut.c, tests/thandle_ut/thandle_flex_user.c, tests/thandle_ut/thandle_user.c, tests/thandle_ut/thandle_ut.c, tests/uuid_ut/uuid_ut.c
=> Use latest C PAL

devdoc/rc_string_requirements.md, inc/azure_c_util/rc_string.h, src/rc_string.c, tests/rc_string_ut/rc_string_ut.c
- Add rc_string tests and code
- Add create_with_move_memory constructor
- Add create_with_custom_free constructor
=> Add rc_string tests and code

build/devops_gated.yml
Remove warnings in C util build
=> Remove warnings in C util build

tests/reals/CMakeLists.txt, tests/reals/real_rc_string.c, tests/reals/real_rc_string.h, tests/reals/real_rc_string_renames.h, tests/reals_ut/azure_c_util_reals_ut.c
=> Add rc_string reals

devdoc/rc_string_requirements.md, inc/azure_c_util/rc_string.h
=> Have PRI_RC_STRING

tests/reals/real_interlocked_hl.c, tests/reals/real_sm.c
Fix reals to do renames for interlocked.h
=> Fix reals to do renames for interlocked.h

inc/c_util/log_critical_and_terminate.h
Fix log critical and terminate to be ... critical
=> Fix log critical and terminate to be ... critical

CMakeLists.txt, build/devops_gated.yml, src/external_command_helper.c, tests/CMakeLists.txt, tests/external_command_helper_int/CMakeLists.txt, tests/external_command_helper_int/external_command_helper_int.c, tests/external_command_helper_int/main.c, tests/external_command_helper_ut/external_command_helper_ut.c, tests/external_command_sample/CMakeLists.txt, tests/external_command_sample/main.c
(apparently win32 _popen is different than posix popen)
=> Add external_command_helper int tests and fix Linux 

CMakeLists.txt, build/devops_gated.yml, inc/c_util/doublylinkedlist.h, src/interlocked_hl.c, src/memory_data.c, tests/external_command_sample/main.c, tests/reals/real_constbuffer.c, tests/reals/real_constbuffer_array.c, tests/reals/real_constbuffer_array_batcher_nv.c, tests/reals/real_doublylinkedlist.c, tests/reals/real_interlocked_hl.c, tests/reals/real_memory_data.c, tests/reals/real_rc_string.c, tests/reals/real_rc_string_array.c, tests/reals/real_singlylinkedlist.c, tests/reals/real_sm.c, tests/reals/real_uuid.c
=> Add includecheck leg

devdoc/rc_string_requirements.md, inc/c_util/rc_string.h, src/rc_string.c, tests/rc_string_ut/rc_string_ut.c, tests/reals/real_rc_string.h, tests/reals/real_rc_string_renames.h
Maybe a better name is the infamous "clone".
=> have rc_string_recreate

CMakeLists.txt, test_helpers/CMakeLists.txt, test_helpers/inc/c_util_test_helpers/rc_string_test_decl.h, test_helpers/inc/c_util_test_helpers/rc_string_test_type.h, test_helpers/inc/c_util_test_helpers/uuid_test_type.h, test_helpers/src/rc_string_test_type.c, test_helpers/src/uuid_test_type.c
Add test helpers from main repo
=> Add test helpers

tests/reals/CMakeLists.txt, tests/reals/real_worker_thread.c, tests/reals/real_worker_thread.h, tests/reals/real_worker_thread_renames.h, tests/reals_ut/c_util_reals_ut.c
=> Add worker thread reals

test_helpers/CMakeLists.txt, test_helpers/inc/c_util_test_helpers/rc_string_test_decl.h
Code was using old THANDLE_DEC_REF instead of THANDLE_ASSIGN to NULL
=> Fix rc_string_test_decl

devdoc/constbuffer_requirements.md
Specification addition in CONSTBUFFER_CreateFromOffsetAndSize.
=> [Specs Change] An optimization in CONSTBUFFER_CreateFromOffsetAndSize

CMakeLists.txt
Add an install step for c_utils and its headers.
=> Add an install step for c_utils and its headers.

tests/async_op_ut/async_op_ut.c, tests/azure_base64_ut/azure_base64_ut.c, tests/buffer_ut/buffer_ut.c, tests/constbuffer_array_batcher_nv_ut/constbuffer_array_batcher_nv_ut.c, tests/constbuffer_array_ut/constbuffer_array_ut.c, tests/constbuffer_ut/constbuffer_ut.c, tests/doublylinkedlist_ut/doublylinkedlist_ut.c, tests/external_command_helper_ut/external_command_helper_ut.c, tests/flags_to_string_int/flags_to_string_int.c, tests/flags_to_string_ut/flags_to_string_ut.c, tests/hash_ut/hash_ut.c, tests/map_ut/map_ut.c, tests/memory_data_ut/memory_data_ut.c, tests/object_lifetime_tracker_ut/object_lifetime_tracker_ut.c, tests/rc_string_array_ut/rc_string_array_ut.c, tests/rc_string_ut/rc_string_ut.c, tests/singlylinkedlist_ut/singlylinkedlist_ut.c, tests/strings_ut/strings_ut.c, tests/tarray_2_int/tarray_2_int.c, tests/tarray_int/tarray_int.c, tests/tarray_ut/tarray_ut.c, tests/thandle_2_ut/thandle_2_ut.c, tests/thandle_tuple_array_ut/thandle_tuple_array_ut.c, tests/thandle_ut/thandle_ut.c, tests/uuid_string_ut/uuid_string_ut.c, tests/worker_thread_ut/worker_thread_ut.c
=> New deps + remove mutex

CMakeLists.txt, build/devops_gated.yml, inc/c_util/hash.h, src/hash.cpp, tests/hash_ut/CMakeLists.txt, tests/hash_ut/hash_under_test.cpp, tests/hash_ut/hash_ut.c, tests/reals/CMakeLists.txt, tests/reals/real_murmurhash2.cpp, tests/reals/real_murmurhash2.h, tests/reals/real_murmurhash2_renames.h
@anporumb 's suggestion, only include the files we are actually using directly into c_util.
=> Remove SMHasher lib and include MurmurHash2 in c_util.

.github/policies/resourceManagement.yml
Test policy with filesMatchPattern
=> Test policy with filesMatchPattern

devdoc/async_op.md, src/async_op.c, src/rc_string.c, tests/async_op_ut/async_op_ut.c
New deps + useTHANDLE_MALLOC_FLEX
=> New deps + useTHANDLE_MALLOC_FLEX

build/devops_gated.yml
=> Run CodeQL 3000

devdoc/tqueue_requirements.md, inc/c_util/tqueue_ll.h, tests/tqueue_ut/tqueue_ut.c
Have an option to have a growable queue
=> Have an option to have a growable queue

devdoc/tqueue_requirements.md, inc/c_util/tqueue.h, inc/c_util/tqueue_ll.h, tests/tqueue_int/tqueue_int.c, tests/tqueue_ut/tqueue_ut.c
- Updated specs to only have one constructor
- Updated specs to lock get count also
- Updated specs with details on moving items when the queue has to be grown
- Implemented code and tests
- Various updates to UTs
=> TQUEUE that can grow: tests and code

build/linux/build_linux.sh, devdoc/tp_worker_thread_requirements.md, src/tp_worker_thread.c, tests/tp_worker_thread_ut/tp_worker_thread_ut.c
Propagating dependency updates
=> Update dependencies + fix tp_worker_thread

devdoc/watchdog_threadpool.md, src/watchdog_threadpool.c, tests/channel_int/channel_int.c, tests/channel_ut/channel_ut.c, tests/watchdog_threadpool_ut/watchdog_threadpool_ut.c
Removing threadpool open and close from C-util
=> C-UTIL:Removed threadpool_open and threadpool_close

tests/tqueue_int/tqueue_int.c
Fixed tqueue_int tests timeout and other issues where pusher_count and popper_count wasn't used.
=> Fixed tqueue_int tests

tests/tqueue_int/tqueue_int.c
Addressing few comments that couldn't be merged earlier.
=> tqueue_int additional changes

tests/tqueue_int/tqueue_int.c
Fix tqueue_int_helgrind timeouts
=> Fix tqueue_int_helgrind timeouts

build/devops_gated.yml
Propagating dependency updates
=> [autogenerated] update dependencies
